name: Daily Video Generator

on:
  schedule:
    - cron: "0 0 * * *"    # 12:00 AM EST
    - cron: "0 3 * * *"    # 03:00 AM EST
    - cron: "0 5 * * *"    # 05:00 AM EST
    - cron: "0 8 * * *"    # 08:00 AM EST
    - cron: "0 10 * * *"   # 10:00 AM EST
    - cron: "0 12 * * *"   # 12:00 PM EST
    - cron: "0 14 * * *"   # 02:00 PM EST
    - cron: "0 17 * * *"   # 05:00 PM EST
    - cron: "0 20 * * *"   # 08:00 PM EST
    - cron: "0 22 * * *"   # 10:00 PM EST
  workflow_dispatch:

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install httpx==0.27.0
          pip install groq==0.11.0
          pip install -r requirements.txt
          pip install httpx==0.27.0 --force-reinstall

      - name: Run pipeline
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
        run: python main.py
